site:
  title: Tenzer.dk

folders:
  include: assets

page_defaults:
  type: none
  url_pattern: '/{slug}/'
  active_menu: blog

site:
  title: Tenzer.dk
  grouping:
    - field: grouping
      key: date
      order: desc

plugins:
  - name: beetle_markdown
  - name: beetle_sass
  - name: beetle_preview
    port: 8000
