site:
  title: Tenzer.dk

folders:
  include: assets

page_defaults:
  type: none
  url_pattern: '/{slug}/'
  active_menu: blog

site:
  title: Tenzer.dk
  grouping:
    - field: grouping
      key: date
      order: desc

plugins:
  - name: beetle_markdown
    extensions:
    - markdown.extensions.admonition
  - name: beetle_sass
  - name: beetle_htmlmin
    args:
      remove_empty_space: True
      remove_comments: True
      remove_optional_attribute_quotes: False
