site:
  title: Tenzer.dk
  domain: tenzer.dk
  grouping:
    - field: grouping
      key: date
      order: desc

folders:
  include: assets

page_defaults:
  type: none
  url_pattern: '/{slug}/'
  active_menu: blog

plugins:
  - name: beetle_markdown
    extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite
  - name: beetle_sass
    output_style: compressed
  - name: beetle_htmlmin
    args:
      remove_empty_space: True
      remove_comments: True
      remove_optional_attribute_quotes: False
  - name: beetle_sitemap
    site: http://tenzer.dk
